export default {
    NEW_CONNECTION: '/public/newConnection',
    LOGIN: '/public/login',
    HOME: '/public/home',
    SUPPORT: '/public/support',
    // PROFILE: '/public/customer/profile',
    PROFILE: '/public/user/detail',
    UPDATE_PROFILE: '/public/customer/update',
    CREATE_REQUEST_LIST: '/public/serviceType/categoryTypeList',
    UPDATE_REFER_FRIENDS: '/public/addReferral',
    SUPPORT_LIST : '/public/support/list',
    DATA_USAGE: '/public/customer/dataUsages',
    MY_PLAN: '/public/customer/currentPlan',
    CREATE_REQUEST_OR_COMPLAINT: '/public/serviceRequest/create',
    ALL_ADDONS: '/public/customer/availableAddOns',
    AVAILABLE_PLANS:'/public/customer/availablePlans',
    RECENT_TRANSACTION: '/public/transaction',
    REVIEW_CURRENT_PLAN: '/public/customer/reviewCurrentPlan',
    INITIATE_PAYMENT: '/public/payment/initiate',
    PAYMENT_TRANSACTION_STATUS: '/public/payment/status',
    GET_RECHARGE: '/public/getRecharge',
    GET_REQUEST_COMPLAINT_TYPES: '/public/serviceType/subCategoryList',
    CHANGE_PASSWORD: '/public/changePassword',
    CHANGE_PLAN: '/public/customer/changePlan',
    ADD_ADDON: '/public/customer/addAddon',
    RESET_PASSWORD: '/public/resetPassword',
    CHANGE_CARD_ORDER: '/public/saveCustomerCardPreference',
    VALIDATE_BANNER_PARAMS: '/public/checkBannerParams'
};